# Cyberpunk Night

[window]
padding = { x = 8, y = 6 }
decorations = "full"  # Sin bordes, full pantalla
opacity = 1.0
blur = false
title = "root@hackermode"

[font]
normal = { family = "Hermit", style = "Regular" }  # Legibilidad hacker
bold = { family = "Hermit", style = "Bold" }
size = 12.0  # Tamaño clásico
offset = { x = -1, y = 0 }

# Configuración del cursor
[cursor]
  style = { shape = "Beam", blinking = "Always" }
  vi_mode_style = "None"
  blink_interval = 500
  unfocused_hollow = true
  thickness = 0.15

[bell]
  animation = "EaseOutExpo"
  duration = 300
  color = "#8A2BE2"
  command = "None"

# Opciones de Mouse
[mouse]
  hide_when_typing = false

# Colores
[colors]
  draw_bold_text_with_bright_colors = true
  [colors.primary]
  background = "0x010B16"  # Azul muy oscuro, casi negro
  foreground = "0x00FFFF"  # Cian brillante

  [colors.normal]
  black = "0x0A0A0A"
  red = "0xFF1A4B"     # Rojo neón intenso
  green = "0x00FF99"   # Verde cibernético
  yellow = "0xFFD700"  # Amarillo dorado
  blue = "0x0066FF"    # Azul eléctrico
  magenta = "0xFF00FF" # Fucsia neón
  cyan = "0x00FFFF"    # Cian radiante
  white = "0xF5F5F5"   # Blanco brillante

  [colors.bright]
  black = "0x333333"
  red = "0xFF5577"
  green = "0x55FFBB"
  yellow = "0xFFFF77"
  blue = "0x6699FF"
  magenta = "0xDD66FF"
  cyan = "0x77FFFF"
  white = "0xFFFFFF"
