# Dark Synthwave

# Fuente
font.normal.family = "Hack Nerd Font Mono"
font.normal.style = "Regular"
font.bold.family = "Hack Nerd Font Mono"
font.bold.style = "Bold"
font.italic.family = "Hack Nerd Font Mono"
font.italic.style = "Italic"
font.size = 13.0
font.offset.x = -1
font.offset.y = -1

# Configuración del cursor
[cursor]
  style = { shape = "Beam", blinking = "Always" }
  vi_mode_style = "None"
  blink_interval = 500
  unfocused_hollow = true
  thickness = 0.15

[bell]
  animation = "EaseOutExpo"
  duration = 300
  color = "#8A2BE2"
  command = "None"

# Opciones de Mouse
[mouse]
  hide_when_typing = false

# Colores del tema
[colors]
  draw_bold_text_with_bright_colors = true
  [colors.primary]
  background = "0x100020"  # Azul noche
  foreground = "0xFF00FF"  # Magenta neón

  [colors.normal]
  black = "0x0A0014"    # Negro con azul profundo
  red = "0xFF0040"      # Rojo eléctrico
  green = "0x00FF80"    # Verde neón
  yellow = "0xFFC300"   # Amarillo brillante
  blue = "0x0040FF"     # Azul neón
  magenta = "0xA000FF"  # Magenta intenso
  cyan = "0x00E6E6"     # Cian vibrante
  white = "0xD0D0D0"    # Blanco suave

  [colors.bright]
  black = "0x444444"    # Gris oscuro
  red = "0xFF6666"      # Rojo brillante
  green = "0x66FF99"    # Verde claro
  yellow = "0xFFFF66"   # Amarillo eléctrico
  blue = "0x6699FF"     # Azul chillón
  magenta = "0xCC66FF"  # Morado brillante
  cyan = "0x66FFFF"     # Cian ultra brillante
  white = "0xFFFFFF"    # Blanco puro
