# Infernal grid

[window]
padding = { x = 8, y = 6 }
decorations = "full"  # Sin bordes, full pantalla
opacity = 1.0
blur = false
title = "root@hackermode"

[font]
normal = { family = "Hermit", style = "Regular" }  # Legibilidad hacker
bold = { family = "Hermit", style = "Bold" }
size = 12.0  # Tamaño clásico
offset = { x = -1, y = 0 }

# Configuración del cursor
[cursor]
  style = { shape = "Block", blinking = "Never" }
  vi_mode_style = "None"
  blink_interval = 500
  unfocused_hollow = true
  thickness = 0.25

[bell]
  animation = "EaseOutExpo"
  duration = 300
  color = "#FF6600"
  command = "None"

# Opciones de Mouse
[mouse]
  hide_when_typing = false

# Colores del tema
[colors]
  draw_bold_text_with_bright_colors = true
  [colors.primary]
  background = "0x000000"  # Negro profundo
  foreground = "0xFF6600"  # Naranja fuego, para destacar el texto

  [colors.normal]
  black = "0x1A1A1A"    # Gris oscuro, casi negro
  red = "0xFF3300"      # Rojo ardiente
  green = "0x99FF00"    # Verde neón, un toque eléctrico
  yellow = "0xFFCC00"   # Amarillo fuego, para resaltar advertencias
  blue = "0x3399FF"     # Azul eléctrico, en la cuadrícula
  magenta = "0xFF00FF"  # Magenta brillante, agresivo
  cyan = "0x00FFFF"     # Cian brillante, añadiendo intensidad
  white = "0xFFFFFF"    # Blanco brillante, para destacar el texto en áreas claras

  [colors.bright]
  black = "0x555555"    # Gris oscuro para el fondo del terminal
  red = "0xFF5555"      # Rojo brillante, para resaltar la entrada de comandos
  green = "0x55FF55"    # Verde neón brillante
  yellow = "0xFFFF00"   # Amarillo brillante para advertencias
  blue = "0x3366CC"     # Azul brillante, para efectos de cuadrícula
  magenta = "0xAA55AA"  # Magenta más suave, para el texto secundario
  cyan = "0x55FFFF"     # Cian vibrante
  white = "0xF2F2F2"    # Blanco suave, para un fondo menos agresivo

