# NECROBYTE Hacker 

# Fuente
font.normal.family = "Terminus"
font.normal.style = "Regular"
font.bold.family = "Terminus"
font.bold.style = "Bold"
font.italic.family = "Terminus"
font.italic.style = "Italic"
font.size = 14.0
font.offset.x = -1
font.offset.y = -1

# Configuración del cursor
[cursor]
  style = { shape = "Beam", blinking = "Always" }
  vi_mode_style = "None"
  blink_interval = 400
  unfocused_hollow = true
  thickness = 0.15

[bell]
  animation = "EaseOutExpo"
  duration = 250
  color = "#00FF00"
  command = "None"

# Opciones de Mouse
[mouse]
  hide_when_typing = false

# Colores del tema
[colors]
  draw_bold_text_with_bright_colors = true
  [colors.primary]
  background = "0x000000"  # Negro absoluto
  foreground = "0x00FF00"  # Verde hacker

  [colors.normal]
  black = "0x111111"    # Negro espectral
  red = "0x880000"      # Rojo sangre muerta
  green = "0x00CC00"    # Verde terminal
  yellow = "0xAAAA00"   # Amarillo cibernético
  blue = "0x003366"     # Azul oscuro digital
  magenta = "0x770077"  # Púrpura necrótico
  cyan = "0x008888"     # Cian espectral
  white = "0xCCCCCC"    # Blanco ceniza

  [colors.bright]
  black = "0x333333"    # Negro necrótico
  red = "0xBB0000"      # Rojo sangre digital
  green = "0x00FF00"    # Verde terminal brillante
  yellow = "0xFFFF00"   # Amarillo radiactivo
  blue = "0x0055AA"     # Azul espectral
  magenta = "0x9900CC"  # Púrpura cibernético
  cyan = "0x00FFFF"     # Cian fantasmal
  white = "0xFFFFFF"    # Blanco digital

