# Necro Terminal

[window]
padding = { x = 8, y = 6 }
decorations = "full"  # Sin bordes, full pantalla
opacity = 1.0
blur = false
title = "root@hackermode"

[font]
normal = { family = "Hermit", style = "Regular" }  # Legibilidad hacker
bold = { family = "Hermit", style = "Bold" }
size = 12.0  # Tamaño clásico
offset = { x = -1, y = 0 }

# Configuración del cursor
[cursor]
  style = { shape = "Beam", blinking = "Always" }
  vi_mode_style = "None"
  blink_interval = 500
  unfocused_hollow = true
  thickness = 0.15

[bell]
  animation = "EaseOutExpo"
  duration = 300
  color = "#00FF00" # Verde radiante

# Opciones de Mouse
[mouse]
  hide_when_typing = false

# Colores del tema
[colors]
  draw_bold_text_with_bright_colors = true
  [colors.primary]
  background = "0x000000"  # Fondo negro
  foreground = "0x00FF00"  # Verde espectral brillante

  [colors.normal]
  black = "0x1A1A1A"        # Negro sucio
  red = "0x770000"           # Rojo sangre
  green = "0x00FF00"         # Verde radiante
  yellow = "0xAAFF00"        # Amarillo envenenado
  blue = "0x0033CC"          # Azul oscuro
  magenta = "0x660066"       # Púrpura oscuro
  cyan = "0x00CCCC"          # Cian maldito
  white = "0x888888"         # Gris sucio

  [colors.bright]
  black = "0x333333"         # Gris oscuro
  red = "0xFF3333"           # Rojo brillante
  green = "0x33FF33"         # Verde neón
  yellow = "0xFFFF33"        # Amarillo fosforescente
  blue = "0x3333FF"          # Azul intenso
  magenta = "0xFF33FF"       # Magenta brillante
  cyan = "0x33FFFF"          # Cian intenso
  white = "0xCCCCCC"         # Gris claro

