# ShadowDOS Terminal

# Fuente
font.normal.family = "Terminus"
font.normal.style = "Regular"
font.bold.family = "Terminus"
font.bold.style = "Bold"
font.italic.family = "Terminus"
font.italic.style = "Italic"
font.size = 14.0
font.offset.x = -1
font.offset.y = 0

# Configuración del cursor
[cursor]
  style = { shape = "Block", blinking = "Always" }
  vi_mode_style = "None"
  blink_interval = 500
  unfocused_hollow = true
  thickness = 0.25

[bell]
  animation = "EaseOutExpo"
  duration = 300
  color = "#FF3300" # Rojo de advertencia

# Opciones de Mouse
[mouse]
  hide_when_typing = false

# Colores del tema
[colors]
  draw_bold_text_with_bright_colors = true
  [colors.primary]
  background = "0x000000"  # Fondo negro profundo
  foreground = "0xFF3300"  # Rojo intenso de alerta

  [colors.normal]
  black = "0x222222"      # Gris oscuro
  red = "0xFF3300"        # Rojo oscuro
  green = "0x33FF33"      # Verde neón
  yellow = "0xFFCC00"     # Amarillo peligroso
  blue = "0x0066FF"       # Azul oscuro
  magenta = "0x9900FF"    # Púrpura brillante
  cyan = "0x00CCCC"       # Cian tenue
  white = "0xBBBBBB"      # Gris claro

  [colors.bright]
  black = "0x555555"      # Gris medio
  red = "0xFF6666"        # Rojo brillante
  green = "0x66FF66"      # Verde brillante
  yellow = "0xFFFF66"     # Amarillo brillante
  blue = "0x3366CC"       # Azul brillante
  magenta = "0xCC66FF"    # Púrpura intenso
  cyan = "0x66FFFF"       # Cian brillante
  white = "0xFFFFFF"      # Blanco brillante

