# Warpzone Terminal

# Fuente
font.normal.family = "Terminus"
font.normal.style = "Regular"
font.bold.family = "Terminus"
font.bold.style = "Bold"
font.italic.family = "Terminus"
font.italic.style = "Italic"
font.size = 14.0
font.offset.x = -1
font.offset.y = -1

# Configuración del cursor
[cursor]
  style = { shape = "Block", blinking = "Always" }
  vi_mode_style = "None"
  blink_interval = 500
  unfocused_hollow = true
  thickness = 0.25

[bell]
  animation = "EaseOutExpo"
  duration = 300
  color = "#8A2BE2"
  command = "None"

# Opciones de Mouse
[mouse]
  hide_when_typing = false

# Colores del tema
[colors]
  draw_bold_text_with_bright_colors = true
  [colors.primary]
  background = "0x000000"  # Fondo negro profundo con distorsión visual
  foreground = "0x00FF00"  # Verde brillante tipo CRT, distorsionado

  [colors.normal]
  black = "0x111111"    # Gris oscuro, como la pantalla de un CRT antiguo
  red = "0xFF0044"      # Rojo brillante tipo error de sistema
  green = "0x00FF00"    # Verde brillante CRT
  yellow = "0xFFFF00"   # Amarillo brillante tipo glitch
  blue = "0x00FFFF"     # Azul neón tipo glitch VHS
  magenta = "0xFF00FF"  # Magenta distorsionado
  cyan = "0x00FFCC"     # Cian brillante tipo distorsión
  white = "0xFFFFFF"    # Blanco brillante y saturado

  [colors.bright]
  black = "0x333333"    # Gris más claro
  red = "0xFF7777"      # Rojo glitch brillante
  green = "0x77FF77"    # Verde más brillante y saturado
  yellow = "0xFFFF77"   # Amarillo más brillante
  blue = "0x7777FF"     # Azul tipo glitch VHS
  magenta = "0xFF77FF"  # Magenta brillante
  cyan = "0x77FFFF"     # Cian más brillante
  white = "0xFFFFFF"    # Blanco saturado tipo CRT

